### ISSUE TITLE
Add descriptive Labels to Counts in Simple Result

### ISSUE THREAD

**Issue by larsebert** [samply/sample-locator#24]
Damit man mal sieht, wie ich mir das vorstelle:
![grafik](https://user-images.githubusercontent.com/65398206/82041720-e8a4ad80-96a8-11ea-8a10-f9f992349a42.png)

**Comment by alexanderkiel** [comment]
@larsebert In your screenshot the number of biobanks is missing? Would you suggest to remove that count from the Simple Result?

**Comment by larsebert** [comment]
No, as you can see, the number of biobanks is below "12 biobanks replied so far ...."
Reason: This is not the main interest of the user, and not expected as result.

**Comment by alexanderkiel** [comment]
> No, as you can see, the number of biobanks is below "12 biobanks replied so far ...."
I see. I also like that you don't show the maximum number of biobanks. We also could replace the progress bar with some more unspecific loading indicator.
